### ISSUE TITLE
Masters have taint NoSchedulabe=true instead of standard node-role.kubernetes.io/master=true

### ISSUE THREAD

**Issue by acjohnson** [ilkilabs/ilke#38]
**Describe the bug**
Instead of keeping with the standard convention of `node-role.kubernetes.io/master=true` the masters are now using a different key (`NoSchedulabe`) which causes upgraded clusters from previous versions to break and manual node edits to fix

https://github.com/ilkilabs/ilke/blob/03e06ac1b700c2171784902998d4d1126725b2ee/roles/post-scripts/tasks/label-hosts.yaml#L32

**Comment by pierrevillard** [comment]
Hi @acjohnson 

Thank you for your feedback! This is very appreciated :)

We added this new key (```NoSchedulabe```) after we added a new host type "storage" used to host OpenEBS pods that provides StorageClass to ILKE.
This helps us to be sure that no end-users applications pods can be scheduled on all no-worker hosts.
Now, we don't plan to add new hosts Types and change tains so upgraded clusters will not be broken anymore.

Maybe there is a better way to do it, so feel free to improve/contribute ! :)

Have a nice day :)
