### ISSUE TITLE
Configure and use logrotate for rotating persistent logs of application inside ILKE. 

### ISSUE THREAD

**Issue by sabrine-hammami** [ilkilabs/ilke#71]
Get log rotation working inside ILKE.

**Comment by pierrevillard** [comment]
Hi @sabrine-hammami 
Today, logs are located on all nodes in the following directories:
  - /var/log/kubernetes
  - /var/log/containers

We should use Logrotate, or a similar tool to enable a logRotation in these directories and let users chose using some variables their own Log rotation policy.

Have a noce day

**Comment by sabrine-hammami** [comment]
Hi @pierreilki 

ok thank you I take note of these indications.
